/// Flutter icons HandeeIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HandeeIcons
///      fonts:
///       - asset: fonts/HandeeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HandeeIcons {
  HandeeIcons._();

  static const _kFontFam = 'HandeeIcons';
  static const String? _kFontPkg = null;

  static const IconData twitter_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_tracking_on = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_tracking_off = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grouped_services = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switch_icon = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData switch_1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData housekeeping = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData expand = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData write = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_tools = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alt_route = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_booked = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gardening = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData washing_machine = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
